name: "Analyze"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: eclairit-1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Analyze
      run: |
        ./script.sh
   
    #- name: Upload Artifact
      #uses: actions/upload-artifact@v3
      #with:
        #name: artefatti
        #path: results.sarif
      
    
    #- name: Upload SARIF file
      #uses: github/codeql-action/upload-sarif@v2
      #with:
        # Path to SARIF file relative to the root of the repository
        #sarif_file: results.sarif
