name: "Analyze"

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: eclairit-1
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Analyze
      run: |
        cd ECLAIR
        # Prepare for build
        ../prepare.sh Debug
        # Analyze the project
        ./analyze.sh MC3 CRC_16
        # Make the directory for ECLAIR project database
        mkdir -p ~/github/$GITHUB_REPOSITORY/$GITHUB_RUN_NUMBER && rm -f ~/github/$GITHUB_REPOSITORY/last_$GITHUB_REF && ln -s ~/github/$GITHUB_REPOSITORY/$GITHUB_RUN_NUMBER ~/github/$GITHUB_REPOSITORY/last_$GITHUB_REF
        # Copy the project database
        scp out_CRC_16_Release_MC3/.data/PROJECT.ecd ~/github/$GITHUB_REPOSITORY/$GITHUB_RUN_NUMBER
        # Publish ECLAIR report link
        echo "https://eclairit.com:3787/fs/home/emelin/github/$GITHUB_REPOSITORY/$GITHUB_RUN_NUMBER/PROJECT.ecd"
        cp report.sarif out_CRC_16_Release_MC3/reports
        #Create the ECLAIR badge
        anybadge --label=ECLAIR --value=default --file=badge.svg
   
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifacts
        paths: |
          - ECLAIR/out_CRC_16_Release_MC3
          - ECLAIR/badge.svg
      
    
    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v2
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: ECLAIR/report.sarif

